### ISSUE TITLE
資料不一致

### ISSUE THREAD

**Issue by isaac-hc-tu** [hswei0/HEDB#4]
學生類表「學13-1、學13-2、學14-1、學14-2」，「學13」是休學人數統計表，「學14」是退學人數統計表，「-1」是以「系(所)為分析單位」；「-2」是以「校」為分析單位，這四張表同一校、同一年，且同一學期的總「在學人數」數字不一。

現階段先都拿掉

**Comment by hswei0** [comment]
This issue is unclear, merging to #5 

> 學生類表「學13-1、學13-2、學14-1、學14-2」，「學13」是休學人數統計表，「學14」是退學人數統計表，「-1」是以「系(所)為分析單位」；「-2」是以「校」為分析單位，這四張表同一校、同一年，且同一學期的總「在學人數」數字不一。
> 
> 現階段先都拿掉
